
spring.application.name=mutualfund-backend
server.port=${PORT:8080}

# MySQL
spring.datasource.url=jdbc:mysql://maglev.proxy.rlwy.net:43038/railway
spring.datasource.username=root
spring.datasource.password=UPgnVeGunDQWgYGZsPfWDPToJOEoxwGs
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rampranaiteja@gmail.com
spring.mail.password=sfif orbq whrb duzs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT
jwt.secret=7a4f2c8d1e6b3f9a5c2d8e4f1a7b3c6d9e2f5a8b4c7d1e3f6a9b2c5d8e1f4a7b
jwt.expiration=86400000

logging.level.com.mutualfund=DEBUG
logging.file.name=logs/app.log

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
